# Generated by Django 5.0.7 on 2026-02-06 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD'), ('Apple', 'Apple Silicon'), ('Other', 'Other')], max_length=20)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('cores', models.PositiveIntegerField(blank=True, null=True)),
                ('threads', models.PositiveIntegerField(blank=True, null=True)),
                ('base_clock', models.DecimalField(blank=True, decimal_places=2, help_text='GHz', max_digits=4, null=True)),
                ('boost_clock', models.DecimalField(blank=True, decimal_places=2, help_text='GHz', max_digits=4, null=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('ram_size', models.PositiveIntegerField(help_text='GB')),
                ('ram_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5'), ('LPDDR4', 'LPDDR4'), ('LPDDR5', 'LPDDR5')], default='DDR4', max_length=20)),
                ('ram_upgradeable', models.BooleanField(default=False)),
                ('max_ram', models.PositiveIntegerField(blank=True, help_text='Maximum RAM in GB', null=True)),
                ('storage_size', models.PositiveIntegerField(help_text='GB')),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD (NVMe/SATA)'), ('HDD', 'HDD'), ('eMMC', 'eMMC'), ('Hybrid', 'Hybrid (SSD + HDD)')], default='SSD', max_length=20)),
                ('additional_storage', models.BooleanField(default=False, help_text='Has additional storage slot')),
                ('display_size', models.DecimalField(decimal_places=2, help_text='Inches', max_digits=4)),
                ('display_resolution', models.CharField(help_text='e.g., 1920x1080', max_length=50)),
                ('refresh_rate', models.PositiveIntegerField(default=60, help_text='Hz')),
                ('panel_type', models.CharField(choices=[('IPS', 'IPS'), ('OLED', 'OLED'), ('TN', 'TN'), ('VA', 'VA'), ('Mini-LED', 'Mini-LED')], default='IPS', max_length=20)),
                ('touchscreen', models.BooleanField(default=False)),
                ('graphics_type', models.CharField(choices=[('Integrated', 'Integrated'), ('Dedicated', 'Dedicated'), ('Hybrid', 'Hybrid')], default='Integrated', max_length=20)),
                ('graphics_model', models.CharField(blank=True, max_length=200)),
                ('graphics_memory', models.PositiveIntegerField(blank=True, help_text='GB (for dedicated)', null=True)),
                ('battery_capacity', models.PositiveIntegerField(blank=True, help_text='Wh', null=True)),
                ('battery_life', models.DecimalField(blank=True, decimal_places=1, help_text='Hours', max_digits=4, null=True)),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=4)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H (mm)', max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('wifi', models.CharField(default='Wi-Fi 6', max_length=50)),
                ('bluetooth', models.CharField(default='5.0', max_length=20)),
                ('ports', models.TextField(blank=True, help_text='USB, HDMI, etc.')),
                ('webcam', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(choices=[('Windows 11', 'Windows 11'), ('Windows 10', 'Windows 10'), ('macOS', 'macOS'), ('Linux', 'Linux'), ('Chrome OS', 'Chrome OS'), ('DOS', 'DOS/No OS')], default='Windows 11', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='laptops/')),
                ('additional_images', models.TextField(blank=True, help_text='Comma-separated image URLs')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Key features, one per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='laptops.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='laptops.category')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laptops.processor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
