# Generated by Django 5.0.7 on 2026-02-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_bio', models.TextField(blank=True, help_text='Short bio about the author')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('excerpt', models.TextField(help_text='Short description for previews', max_length=300)),
                ('content', models.TextField(help_text='Full article content (supports HTML)')),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='laptops.laptop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
