# Generated by Django 5.0.7 on 2024-08-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_laptop_average_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='average_rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.laptop'),
        ),
    ]
