# Generated by Django 5.0.7 on 2026-02-06 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, help_text='Alert when price drops below this', max_digits=10)),
                ('retailer', models.CharField(blank=True, choices=[('amazon', 'Amazon'), ('bestbuy', 'Best Buy'), ('newegg', 'Newegg'), ('walmart', 'Walmart'), ('direct', 'Direct from Manufacturer'), ('other', 'Other')], help_text='Specific retailer or any', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='laptops.laptop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'laptop', 'retailer')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retailer', models.CharField(choices=[('amazon', 'Amazon'), ('bestbuy', 'Best Buy'), ('newegg', 'Newegg'), ('walmart', 'Walmart'), ('direct', 'Direct from Manufacturer'), ('other', 'Other')], default='direct', max_length=20)),
                ('retailer_url', models.URLField(blank=True, help_text='Affiliate link')),
                ('in_stock', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='laptops.laptop')),
            ],
            options={
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['laptop', '-recorded_at'], name='laptops_pri_laptop__1897bc_idx')],
            },
        ),
    ]
