# Generated by Django 5.0.7 on 2026-02-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_pricealert_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='laptop_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Main display image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='laptops.laptop')),
            ],
            options={
                'verbose_name': 'Laptop Image',
                'verbose_name_plural': 'Laptop Images',
                'ordering': ['-is_primary', 'order', '-uploaded_at'],
            },
        ),
    ]
