# Generated by Django 5.0.7 on 2024-08-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0004_remove_laptop_average_rating_alter_rating_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='review',
        ),
    ]
