"""
Database Population Script for LaptopXplorer
Run this in Django shell with: python manage.py shell < populate_data.py
Or copy and paste into: python manage.py shell
"""

from laptops.models import Brand, Category, Processor, Laptop
from decimal import Decimal

print("🚀 Starting database population...")

# Create Brands (using get_or_create to avoid duplicates)
print("📦 Creating brands...")
brands_data = [
    {'name': 'HP', 'description': 'American multinational information technology company', 'website': 'https://www.hp.com'},
    {'name': 'Dell', 'description': 'American technology company', 'website': 'https://www.dell.com'},
    {'name': 'Lenovo', 'description': 'Chinese multinational technology company', 'website': 'https://www.lenovo.com'},
    {'name': 'Apple', 'description': 'American multinational technology company', 'website': 'https://www.apple.com'},
    {'name': 'Asus', 'description': 'Taiwanese multinational computer hardware company', 'website': 'https://www.asus.com'},
    {'name': 'Acer', 'description': 'Taiwanese multinational hardware corporation', 'website': 'https://www.acer.com'},
    {'name': 'MSI', 'description': 'Taiwanese multinational IT corporation', 'website': 'https://www.msi.com'},
    {'name': 'Razer', 'description': 'Gaming hardware manufacturing company', 'website': 'https://www.razer.com'},
]

brands = {}
for brand_data in brands_data:
    brand, created = Brand.objects.get_or_create(name=brand_data['name'], defaults=brand_data)
    brands[brand.name] = brand
print(f"  ✅ {len(brands)} brands ready")

# Create Categories
print("📁 Creating categories...")
categories_data = [
    {'name': 'Gaming', 'description': 'High-performance laptops for gaming', 'icon': 'fas fa-gamepad'},
    {'name': 'Business', 'description': 'Professional laptops for business use', 'icon': 'fas fa-briefcase'},
    {'name': 'Ultrabook', 'description': 'Thin and light premium laptops', 'icon': 'fas fa-feather'},
    {'name': 'Budget', 'description': 'Affordable laptops for everyday use', 'icon': 'fas fa-dollar-sign'},
    {'name': 'Workstation', 'description': 'Powerful laptops for professional work', 'icon': 'fas fa-cogs'},
    {'name': 'Student', 'description': 'Laptops designed for students', 'icon': 'fas fa-graduation-cap'},
]

categories = {}
for cat_data in categories_data:
    category, created = Category.objects.get_or_create(name=cat_data['name'], defaults=cat_data)
    categories[category.name] = category
print(f"  ✅ {len(categories)} categories ready")

# Create Processors
print("⚙️  Creating processors...")
processors_data = [
    # Intel
    {'name': 'Intel Core i3-1215U', 'brand': 'Intel', 'generation': '12th Gen', 'cores': 6, 'threads': 8, 'base_clock': Decimal('1.2'), 'boost_clock': Decimal('4.4')},
    {'name': 'Intel Core i5-1235U', 'brand': 'Intel', 'generation': '12th Gen', 'cores': 10, 'threads': 12, 'base_clock': Decimal('1.3'), 'boost_clock': Decimal('4.4')},
    {'name': 'Intel Core i5-12450H', 'brand': 'Intel', 'generation': '12th Gen', 'cores': 8, 'threads': 12, 'base_clock': Decimal('2.0'), 'boost_clock': Decimal('4.4')},
    {'name': 'Intel Core i7-1255U', 'brand': 'Intel', 'generation': '12th Gen', 'cores': 10, 'threads': 12, 'base_clock': Decimal('1.7'), 'boost_clock': Decimal('4.7')},
    {'name': 'Intel Core i7-12650H', 'brand': 'Intel', 'generation': '12th Gen', 'cores': 10, 'threads': 16, 'base_clock': Decimal('2.3'), 'boost_clock': Decimal('4.7')},
    {'name': 'Intel Core i7-13700H', 'brand': 'Intel', 'generation': '13th Gen', 'cores': 14, 'threads': 20, 'base_clock': Decimal('2.4'), 'boost_clock': Decimal('5.0')},
    {'name': 'Intel Core i9-13900H', 'brand': 'Intel', 'generation': '13th Gen', 'cores': 14, 'threads': 20, 'base_clock': Decimal('2.6'), 'boost_clock': Decimal('5.4')},
    # AMD
    {'name': 'AMD Ryzen 5 5500U', 'brand': 'AMD', 'generation': '5000 Series', 'cores': 6, 'threads': 12, 'base_clock': Decimal('2.1'), 'boost_clock': Decimal('4.0')},
    {'name': 'AMD Ryzen 5 5600H', 'brand': 'AMD', 'generation': '5000 Series', 'cores': 6, 'threads': 12, 'base_clock': Decimal('3.3'), 'boost_clock': Decimal('4.2')},
    {'name': 'AMD Ryzen 7 5800H', 'brand': 'AMD', 'generation': '5000 Series', 'cores': 8, 'threads': 16, 'base_clock': Decimal('3.2'), 'boost_clock': Decimal('4.4')},
    {'name': 'AMD Ryzen 7 7735HS', 'brand': 'AMD', 'generation': '7000 Series', 'cores': 8, 'threads': 16, 'base_clock': Decimal('3.2'), 'boost_clock': Decimal('4.75')},
    # Apple
    {'name': 'Apple M1', 'brand': 'Apple', 'generation': 'M1', 'cores': 8, 'threads': 8, 'base_clock': Decimal('3.2'), 'boost_clock': Decimal('3.2')},
    {'name': 'Apple M2', 'brand': 'Apple', 'generation': 'M2', 'cores': 8, 'threads': 8, 'base_clock': Decimal('3.5'), 'boost_clock': Decimal('3.5')},
]

processors = {}
for proc_data in processors_data:
    processor, created = Processor.objects.get_or_create(name=proc_data['name'], defaults=proc_data)
    processors[processor.name] = processor
print(f"  ✅ {len(processors)} processors ready")

# Create 50 Laptops
print("💻 Creating laptops...")
laptops = [
    # HP Laptops (6)
    {'name': 'Pavilion 15-eg3000', 'brand': brands['HP'], 'category': categories['Student'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.75'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('649.99'), 'in_stock': True, 'battery_life': Decimal('7.5')},
    {'name': 'Victus 16', 'brand': brands['HP'], 'category': categories['Gaming'], 'processor': processors['Intel Core i5-12450H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('16.1'), 'display_resolution': '1920x1080', 'refresh_rate': 144, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3050', 'graphics_memory': 4, 'weight': Decimal('2.46'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('899.99'), 'in_stock': True, 'battery_life': Decimal('5.5')},
    {'name': 'Envy x360 15', 'brand': brands['HP'], 'category': categories['Business'], 'processor': processors['AMD Ryzen 7 5800H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'touchscreen': True, 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.82'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1099.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    {'name': 'EliteBook 840 G9', 'brand': brands['HP'], 'category': categories['Business'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.36'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1399.99'), 'in_stock': True, 'battery_life': Decimal('12.0')},
    {'name': 'Omen 17', 'brand': brands['HP'], 'category': categories['Gaming'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('17.3'), 'display_resolution': '2560x1440', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4070', 'graphics_memory': 8, 'weight': Decimal('2.78'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2199.99'), 'in_stock': True, 'battery_life': Decimal('4.5')},
    {'name': 'Pavilion Gaming 15', 'brand': brands['HP'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 5 5600H'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 144, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA GTX 1650', 'graphics_memory': 4, 'weight': Decimal('2.23'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.0', 'operating_system': 'Windows 11', 'price': Decimal('749.99'), 'in_stock': True, 'battery_life': Decimal('5.5')},
    
    # Dell Laptops (8)
    {'name': 'Inspiron 15 3520', 'brand': brands['Dell'], 'category': categories['Budget'], 'processor': processors['Intel Core i3-1215U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'TN', 'graphics_type': 'Integrated', 'graphics_model': 'Intel UHD Graphics', 'weight': Decimal('1.85'), 'wifi': 'Wi-Fi 5', 'bluetooth': '5.0', 'operating_system': 'Windows 11', 'price': Decimal('449.99'), 'in_stock': True, 'battery_life': Decimal('6.0')},
    {'name': 'XPS 13 9320', 'brand': brands['Dell'], 'category': categories['Ultrabook'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('13.4'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.27'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1299.99'), 'in_stock': True, 'battery_life': Decimal('11.0')},
    {'name': 'XPS 15 9530', 'brand': brands['Dell'], 'category': categories['Workstation'], 'processor': processors['Intel Core i7-13700H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '3456x2160', 'refresh_rate': 60, 'panel_type': 'OLED', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4050', 'graphics_memory': 6, 'weight': Decimal('1.86'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2499.99'), 'in_stock': True, 'battery_life': Decimal('8.0')},
    {'name': 'G15 5520', 'brand': brands['Dell'], 'category': categories['Gaming'], 'processor': processors['Intel Core i7-12650H'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3060', 'graphics_memory': 6, 'weight': Decimal('2.51'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1399.99'), 'in_stock': True, 'battery_life': Decimal('5.0')},
    {'name': 'Latitude 5430', 'brand': brands['Dell'], 'category': categories['Business'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.44'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('899.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    {'name': 'Inspiron 14 Plus', 'brand': brands['Dell'], 'category': categories['Student'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2240x1400', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.59'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('799.99'), 'in_stock': True, 'battery_life': Decimal('9.0')},
    {'name': 'Alienware m15 R7', 'brand': brands['Dell'], 'category': categories['Gaming'], 'processor': processors['Intel Core i7-12650H'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3070 Ti', 'graphics_memory': 8, 'weight': Decimal('2.42'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1899.99'), 'in_stock': True, 'battery_life': Decimal('4.5')},
    {'name': 'Precision 5570', 'brand': brands['Dell'], 'category': categories['Workstation'], 'processor': processors['Intel Core i7-12650H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX A2000', 'graphics_memory': 4, 'weight': Decimal('1.78'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('2199.99'), 'in_stock': True, 'battery_life': Decimal('8.0')},
    
    # Lenovo Laptops (8)
    {'name': 'IdeaPad 3 15ITL6', 'brand': brands['Lenovo'], 'category': categories['Budget'], 'processor': processors['Intel Core i3-1215U'], 'ram_size': 4, 'ram_type': 'DDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'TN', 'graphics_type': 'Integrated', 'graphics_model': 'Intel UHD Graphics', 'weight': Decimal('1.7'), 'wifi': 'Wi-Fi 5', 'bluetooth': '5.0', 'operating_system': 'Windows 11', 'price': Decimal('399.99'), 'in_stock': True, 'battery_life': Decimal('7.0')},
    {'name': 'ThinkPad X1 Carbon Gen 11', 'brand': brands['Lenovo'], 'category': categories['Business'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.12'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1599.99'), 'in_stock': True, 'battery_life': Decimal('15.0')},
    {'name': 'Legion 5 Pro', 'brand': brands['Lenovo'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 7 7735HS'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('16.0'), 'display_resolution': '2560x1600', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4060', 'graphics_memory': 8, 'weight': Decimal('2.5'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1699.99'), 'in_stock': True, 'battery_life': Decimal('6.0')},
    {'name': 'Legion Pro 7i', 'brand': brands['Lenovo'], 'category': categories['Gaming'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('16.0'), 'display_resolution': '2560x1600', 'refresh_rate': 240, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4080', 'graphics_memory': 12, 'weight': Decimal('2.8'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2799.99'), 'in_stock': True, 'battery_life': Decimal('4.0')},
    {'name': 'ThinkBook 14 G6', 'brand': brands['Lenovo'], 'category': categories['Business'], 'processor': processors['AMD Ryzen 7 7735HS'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.4'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('799.99'), 'in_stock': True, 'battery_life': Decimal('11.0')},
    {'name': 'IdeaPad Flex 5', 'brand': brands['Lenovo'], 'category': categories['Student'], 'processor': processors['AMD Ryzen 5 5500U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'touchscreen': True, 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.5'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.1', 'operating_system': 'Windows 11', 'price': Decimal('599.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    {'name': 'Yoga Slim 7 Pro', 'brand': brands['Lenovo'], 'category': categories['Ultrabook'], 'processor': processors['AMD Ryzen 7 5800H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2880x1800', 'refresh_rate': 90, 'panel_type': 'OLED', 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.38'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1299.99'), 'in_stock': True, 'battery_life': Decimal('12.0')},
    {'name': 'ThinkPad P1 Gen 5', 'brand': brands['Lenovo'], 'category': categories['Workstation'], 'processor': processors['Intel Core i7-12650H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('16.0'), 'display_resolution': '2560x1600', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX A2000', 'graphics_memory': 8, 'weight': Decimal('1.81'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('2299.99'), 'in_stock': True, 'battery_life': Decimal('7.5')},
    
    # Apple Laptops (4)
    {'name': 'MacBook Air M1', 'brand': brands['Apple'], 'category': categories['Ultrabook'], 'processor': processors['Apple M1'], 'ram_size': 8, 'ram_type': 'LPDDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('13.3'), 'display_resolution': '2560x1600', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Apple M1 GPU', 'weight': Decimal('1.29'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.0', 'operating_system': 'macOS', 'price': Decimal('999.99'), 'in_stock': True, 'battery_life': Decimal('18.0')},
    {'name': 'MacBook Air M2', 'brand': brands['Apple'], 'category': categories['Ultrabook'], 'processor': processors['Apple M2'], 'ram_size': 8, 'ram_type': 'LPDDR5', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('13.6'), 'display_resolution': '2560x1664', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Apple M2 GPU', 'weight': Decimal('1.24'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.3', 'operating_system': 'macOS', 'price': Decimal('1199.99'), 'in_stock': True, 'battery_life': Decimal('18.0')},
    {'name': 'MacBook Air M2 15"', 'brand': brands['Apple'], 'category': categories['Ultrabook'], 'processor': processors['Apple M2'], 'ram_size': 8, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.3'), 'display_resolution': '2880x1864', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Apple M2 GPU', 'weight': Decimal('1.51'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.3', 'operating_system': 'macOS', 'price': Decimal('1499.99'), 'in_stock': True, 'battery_life': Decimal('18.0')},
    {'name': 'MacBook Pro 14 M2', 'brand': brands['Apple'], 'category': categories['Workstation'], 'processor': processors['Apple M2'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.2'), 'display_resolution': '3024x1964', 'refresh_rate': 120, 'panel_type': 'Mini-LED', 'graphics_type': 'Integrated', 'graphics_model': 'Apple M2 GPU', 'weight': Decimal('1.6'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'macOS', 'price': Decimal('1999.99'), 'in_stock': True, 'battery_life': Decimal('17.0')},
    
    # Asus Laptops (8)
    {'name': 'VivoBook 15', 'brand': brands['Asus'], 'category': categories['Student'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.7'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('599.99'), 'in_stock': True, 'battery_life': Decimal('8.0')},
    {'name': 'ZenBook 14 OLED', 'brand': brands['Asus'], 'category': categories['Ultrabook'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2880x1800', 'refresh_rate': 90, 'panel_type': 'OLED', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.39'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1099.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    {'name': 'ROG Strix G16', 'brand': brands['Asus'], 'category': categories['Gaming'], 'processor': processors['Intel Core i7-13700H'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('16.0'), 'display_resolution': '1920x1200', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4060', 'graphics_memory': 8, 'weight': Decimal('2.5'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('1699.99'), 'in_stock': True, 'battery_life': Decimal('5.5')},
    {'name': 'ROG Zephyrus G14', 'brand': brands['Asus'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 7 7735HS'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2560x1600', 'refresh_rate': 120, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'AMD Radeon RX 6700S', 'graphics_memory': 8, 'weight': Decimal('1.65'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1799.99'), 'in_stock': True, 'battery_life': Decimal('8.0')},
    {'name': 'TUF Gaming A15', 'brand': brands['Asus'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 7 5800H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 144, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3060', 'graphics_memory': 6, 'weight': Decimal('2.3'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1199.99'), 'in_stock': True, 'battery_life': Decimal('6.0')},
    {'name': 'ProArt Studiobook 16', 'brand': brands['Asus'], 'category': categories['Workstation'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('16.0'), 'display_resolution': '3200x2000', 'refresh_rate': 120, 'panel_type': 'OLED', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4070', 'graphics_memory': 8, 'weight': Decimal('2.4'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2799.99'), 'in_stock': True, 'battery_life': Decimal('6.0')},
    {'name': 'VivoBook Pro 15', 'brand': brands['Asus'], 'category': categories['Student'], 'processor': processors['AMD Ryzen 5 5600H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA GTX 1650', 'graphics_memory': 4, 'weight': Decimal('1.8'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.0', 'operating_system': 'Windows 11', 'price': Decimal('799.99'), 'in_stock': True, 'battery_life': Decimal('7.0')},
    {'name': 'ROG Flow X13', 'brand': brands['Asus'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 7 7735HS'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('13.4'), 'display_resolution': '1920x1200', 'refresh_rate': 120, 'panel_type': 'IPS', 'touchscreen': True, 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.3'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1499.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    
    # Acer Laptops (8)
    {'name': 'Aspire 5', 'brand': brands['Acer'], 'category': categories['Budget'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.77'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.1', 'operating_system': 'Windows 11', 'price': Decimal('549.99'), 'in_stock': True, 'battery_life': Decimal('7.5')},
    {'name': 'Swift 3', 'brand': brands['Acer'], 'category': categories['Ultrabook'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'LPDDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.2'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.1', 'operating_system': 'Windows 11', 'price': Decimal('799.99'), 'in_stock': True, 'battery_life': Decimal('12.0')},
    {'name': 'Nitro 5', 'brand': brands['Acer'], 'category': categories['Gaming'], 'processor': processors['Intel Core i5-12450H'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 144, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3050 Ti', 'graphics_memory': 4, 'weight': Decimal('2.5'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.1', 'operating_system': 'Windows 11', 'price': Decimal('849.99'), 'in_stock': True, 'battery_life': Decimal('5.0')},
    {'name': 'Predator Helios 300', 'brand': brands['Acer'], 'category': categories['Gaming'], 'processor': processors['Intel Core i7-13700H'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '2560x1440', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4060', 'graphics_memory': 8, 'weight': Decimal('2.6'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1599.99'), 'in_stock': True, 'battery_life': Decimal('4.5')},
    {'name': 'Swift X', 'brand': brands['Acer'], 'category': categories['Student'], 'processor': processors['AMD Ryzen 5 5500U'], 'ram_size': 8, 'ram_type': 'LPDDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA GTX 1650', 'graphics_memory': 4, 'weight': Decimal('1.39'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.0', 'operating_system': 'Windows 11', 'price': Decimal('699.99'), 'in_stock': True, 'battery_life': Decimal('11.0')},
    {'name': 'Aspire 3', 'brand': brands['Acer'], 'category': categories['Budget'], 'processor': processors['AMD Ryzen 5 5500U'], 'ram_size': 4, 'ram_type': 'DDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'TN', 'graphics_type': 'Integrated', 'graphics_model': 'AMD Radeon', 'weight': Decimal('1.9'), 'wifi': 'Wi-Fi 5', 'bluetooth': '4.2', 'operating_system': 'Windows 11', 'price': Decimal('379.99'), 'in_stock': True, 'battery_life': Decimal('6.5')},
    {'name': 'ConceptD 7', 'brand': brands['Acer'], 'category': categories['Workstation'], 'processor': processors['Intel Core i7-12650H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '3840x2160', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX A5500', 'graphics_memory': 16, 'weight': Decimal('2.5'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('3499.99'), 'in_stock': True, 'battery_life': Decimal('7.0')},
    {'name': 'Chromebook Spin 714', 'brand': brands['Acer'], 'category': categories['Student'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 8, 'ram_type': 'LPDDR4', 'storage_size': 256, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'touchscreen': True, 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.4'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Chrome OS', 'price': Decimal('699.99'), 'in_stock': True, 'battery_life': Decimal('12.0')},
    
    # MSI Laptops (4)
    {'name': 'Modern 14', 'brand': brands['MSI'], 'category': categories['Business'], 'processor': processors['Intel Core i5-1235U'], 'ram_size': 16, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '1920x1080', 'refresh_rate': 60, 'panel_type': 'IPS', 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.4'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('749.99'), 'in_stock': True, 'battery_life': Decimal('10.0')},
    {'name': 'GF63 Thin', 'brand': brands['MSI'], 'category': categories['Gaming'], 'processor': processors['Intel Core i5-12450H'], 'ram_size': 8, 'ram_type': 'DDR4', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '1920x1080', 'refresh_rate': 144, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 3050', 'graphics_memory': 4, 'weight': Decimal('1.86'), 'wifi': 'Wi-Fi 6', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('799.99'), 'in_stock': True, 'battery_life': Decimal('5.0')},
    {'name': 'Stealth 14 Studio', 'brand': brands['MSI'], 'category': categories['Gaming'], 'processor': processors['Intel Core i7-13700H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2560x1600', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4060', 'graphics_memory': 8, 'weight': Decimal('1.7'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('1899.99'), 'in_stock': True, 'battery_life': Decimal('7.0')},
    {'name': 'Raider GE78', 'brand': brands['MSI'], 'category': categories['Gaming'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('17.3'), 'display_resolution': '2560x1440', 'refresh_rate': 240, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4080', 'graphics_memory': 12, 'weight': Decimal('3.1'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('3299.99'), 'in_stock': True, 'battery_life': Decimal('3.5')},
    
    # Razer Laptops (4)
    {'name': 'Book 13', 'brand': brands['Razer'], 'category': categories['Ultrabook'], 'processor': processors['Intel Core i7-1255U'], 'ram_size': 16, 'ram_type': 'LPDDR5', 'storage_size': 512, 'storage_type': 'SSD', 'display_size': Decimal('13.4'), 'display_resolution': '1920x1200', 'refresh_rate': 60, 'panel_type': 'IPS', 'touchscreen': True, 'graphics_type': 'Integrated', 'graphics_model': 'Intel Iris Xe', 'weight': Decimal('1.34'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.2', 'operating_system': 'Windows 11', 'price': Decimal('1499.99'), 'in_stock': True, 'battery_life': Decimal('11.0')},
    {'name': 'Blade 14', 'brand': brands['Razer'], 'category': categories['Gaming'], 'processor': processors['AMD Ryzen 7 7735HS'], 'ram_size': 16, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('14.0'), 'display_resolution': '2560x1440', 'refresh_rate': 165, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4060', 'graphics_memory': 8, 'weight': Decimal('1.84'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2299.99'), 'in_stock': True, 'battery_life': Decimal('7.0')},
    {'name': 'Blade 15 Advanced', 'brand': brands['Razer'], 'category': categories['Gaming'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 1024, 'storage_type': 'SSD', 'display_size': Decimal('15.6'), 'display_resolution': '2560x1440', 'refresh_rate': 240, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4070', 'graphics_memory': 8, 'weight': Decimal('2.01'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('2899.99'), 'in_stock': True, 'battery_life': Decimal('6.0')},
    {'name': 'Blade 17', 'brand': brands['Razer'], 'category': categories['Gaming'], 'processor': processors['Intel Core i9-13900H'], 'ram_size': 32, 'ram_type': 'DDR5', 'storage_size': 2048, 'storage_type': 'SSD', 'display_size': Decimal('17.3'), 'display_resolution': '2560x1440', 'refresh_rate': 240, 'panel_type': 'IPS', 'graphics_type': 'Dedicated', 'graphics_model': 'NVIDIA RTX 4090', 'graphics_memory': 16, 'weight': Decimal('2.75'), 'wifi': 'Wi-Fi 6E', 'bluetooth': '5.3', 'operating_system': 'Windows 11', 'price': Decimal('3999.99'), 'in_stock': True, 'battery_life': Decimal('5.0')},
]

laptop_count = 0
for laptop_data in laptops:
    # Use model_number as unique identifier (combine brand + name)
    model_number = f"{laptop_data['brand'].name}-{laptop_data['name']}"
    laptop, created = Laptop.objects.get_or_create(
        name=laptop_data['name'],
        brand=laptop_data['brand'],
        defaults=laptop_data
    )
    if created:
        laptop_count += 1

print(f"✅ {laptop_count} new laptops added ({Laptop.objects.count()} total in database)")

# Summary
print("\n" + "="*50)
print("🎉 DATABASE POPULATED SUCCESSFULLY!")
print("="*50)
print(f"📊 Summary:")
print(f"  • Brands: {Brand.objects.count()}")
print(f"  • Categories: {Category.objects.count()}")
print(f"  • Processors: {Processor.objects.count()}")
print(f"  • Laptops: {Laptop.objects.count()}")
print("\n✨ You can now browse your laptops at http://localhost:8000/laptops/")
print("🔧 Admin panel: http://localhost:8000/admin")
